name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: "JS v0.2.2" # v0.2.2 == commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@271a688dffed8d09db213eb2f322beebe6d56433
    with:
      skip-node18: true
