name: Upload standalone file to GitHub Releases
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm install -g npm
      - run: npm ci
      - run: npm run build
      - run: npm run build:release
      - run: gh release upload ${{ github.event.release.tag_name }} test/build/noble-secp256k1.min.js test/build/noble-secp256k1.min.js.gz
        env:
          GH_TOKEN: ${{ github.token }}
